services:
  - type: web
    name: tejas-portfolio
    runtime: node
    rootDir: tejas-portfolio
    buildCommand: npm ci && npm run build
    startCommand: npm run start -- -p $PORT
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
